set_bridge:
  target:
    device:
      integration: huesyncbox
    entity:
      integration: huesyncbox
  fields:
    bridge_id:
      example: 001788FFFE000000
      required: true
      selector:
        text:
    bridge_username:
      example: WB9xS1t0Baw-8ZqYKMcEhOaKRU42E84-NZBXwcIL
      required: true
      selector:
        text:
    bridge_clientkey:
      example: 00112233445566778899AABBCCDDEEFF
      required: true
      selector:
        text: