set_bridge:
  target:
    device:
      integration: huesyncbox
    entity:
      integration: huesyncbox
  fields:
    bridge_id:
      example: 001788FFFE000000
      required: true
      selector:
        text:
    bridge_username:
      example: WB9xS1t0Baw-8ZqYKMcEhOaKRU42E84-NZBXwcIL
      required: true
      selector:
        text:
    bridge_clientkey:
      example: 00112233445566778899AABBCCDDEEFF
      required: true
      selector:
        text:

set_sync_state:
  target:
    device:
      integration: huesyncbox
    entity:
      integration: huesyncbox
  fields:
    sync:
      example: true
      selector:
        boolean:
    sync_toggle:
      example: true
      selector:
        boolean:
    brightness:
      example: 42
      selector:
        number:
          min: 0.0
          max: 100.0
          step: 0.5
          mode: slider
    brightness_step:
      example: -20
      selector:
        number:
          min: -100.0
          max: 100.0
          step: 0.5
          mode: slider
    mode:
      example: video
      selector:
        select:
          translation_key: modes
          options:
            - video
            - music
            - game
    mode_next:
      example: true
      selector:
        boolean:
    mode_prev:
      example: true
      selector:
        boolean:
    intensity:
      example: high
      selector:
        select:
          translation_key: "intensities"
          options:
            - subtle
            - moderate
            - high
            - intense
    intensity_next:
      example: true
      selector:
        boolean:
    intensity_prev:
      example: true
      selector:
        boolean:
    input:
      example: input1
      selector:
        select:
          translation_key: "inputs"
          options:
            - input1
            - input2
            - input3
            - input4
    input_next:
      example: true
      selector:
        boolean:
    input_prev:
      example: true
      selector:
        boolean:
    entertainment_area:
      example: TV Area
      selector:
        text: