name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: Hassfest
        uses: home-assistant/actions/hassfest@master
      - name: HACS validation
        uses: "hacs/integration/action@master"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CATEGORY: "integration"

  release:
    if: ${{ startsWith(github.ref, 'refs/tags/releases/v') }}
    needs: validate
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Zip custom components dir
        working-directory: "custom_components"
        run: zip -r huesyncbox.zip huesyncbox/*
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1  # Official Github action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
#          body: |
#            Changes in this Release
#            - First Change
#            - Second Change
          draft: false
          prerelease: false
